#!/usr/bin/env bash
# Creates the file `/var/run/myscript.pid` containing this file's PID
# Displays `To infinity and beyond` indefinitely
# Displays `I hate the kill command` when receiving a SIGTERM signal
# Displays `Y U no love me?!` when receiving a SIGINT signal
# Deletes the file `/var/run/myscript.pid` and
# terminates itself when receiving a SIGQUIT or SIGTERM signal

echo $$
echo "$$" > /var/run/myscript.pid

function termfunc() {
	rm /var/run/myscript.pid
	exit
}


while true
do
	echo "To infinity and beyond"
	sleep 3
	trap "echo 'I hate the kill command' && termfunc" SIGTERM
	trap "echo 'Y U no love me?!'" SIGINT
	trap "termfunc" SIGQUIT
done
