#!/usr/bin/env bash
# Print "bad luck" for the 4th iteration
# Print "good luck" for the 8th iteration
# Print "Best School" for the other iterations

counter=1

while [ $counter -lt 11 ]
do
	if [ $counter -eq 4 ]
	then
		echo "bad luck"
	elif [ $counter -eq 8 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	((counter++))
done
