#!/usr/bin/env bash
# Print numbers 1 to 20 and
# Print custom messages for 4th, 9th and 17th iterations

counter=1

while [ $counter -le 20 ]; do
	echo "$counter"
	if [ $counter -eq 4 ]; then
		echo "bad luck from China"
	elif [ $counter -eq 9 ]; then
		echo "bad luck from Japan"
	elif [ $counter -eq 17 ]; then
		echo "bad luck from Italy"
	fi
	((counter++))
done
